// auto-generated by deployPerps.ts
export const deployed = {
  baseSepolia: { oracle: '0x54105f0f40c6190f982c71836aCc25c91030CADD', perps: '0x84928F62e13C272d3553427b8753A8ae8Fa3324D' },
  base: { oracle: '', perps: '' }
} as const;
