// auto-generated by deployPerps.ts and extended for multi-market
export const deployed = {
  baseSepolia: {
    btcd: { oracle: '0x54105f0f40c6190f982c71836aCc25c91030CADD', perps: '0xa3909Efe241635e4D733054c6929B1FB75840128' },
    random: { oracle: '0x1194a6CdE8AE282739eC9Eb7E5374aaAb5062309', perps: '0xD0A3Babe37a65DC03757Be43c92c530062c2E39f' }
  },
  base: {
    btcd: { oracle: '', perps: '' },
    random: { oracle: '', perps: '' }
  }
} as const;
