// auto-generated by deployPerps.ts
export const deployed = {
  baseSepolia: { oracle: '0x54105f0f40c6190f982c71836aCc25c91030CADD', perps: '0xa3909Efe241635e4D733054c6929B1FB75840128' },
  base: { oracle: '', perps: '' }
} as const;
